# Copyright (c) 2026 SpeakCV Team
# This project is licensed under the MIT License.
# See the LICENSE file in the project root for more information.

services:
  # --- BACKEND ---
  backend:
    build: ./src/backend
    container_name: speakcv_backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:thanhhoang%40123@host.docker.internal:3306/speakcv

  # --- FRONTEND ---
  frontend:
    build: ./src/frontend
    container_name: speakcv_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "rm -rf /app/.next && npm install && npx next dev -H 0.0.0.0"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development

volumes:
  frontend_node_modules: