# Copyright (c) 2026 SpeakCV Team
# This project is licensed under the MIT License.
# See the LICENSE file in the project root for more information.

import os
import io
import urllib.parse
import requests
import time
import json
import re
import edge_tts
from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, Request
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from dotenv import load_dotenv

from .. import models
from ..database import sql_models
from ..database.database import get_db
from .profile import get_current_user
from ..ai_service import call_ai_chat

load_dotenv() 

router = APIRouter()

guest_ip_tracker = {}

api_key = os.getenv("OPENAI_API_KEY")

def clean_and_parse_json(raw_text: str):
    """Clean garbage characters generated by AI before parsing JSON"""
    cleaned = re.sub(r'^```json\s*', '', raw_text, flags=re.IGNORECASE)
    cleaned = re.sub(r'^```\s*', '', cleaned)
    cleaned = re.sub(r'\s*```$', '', cleaned)
    
    cleaned = re.sub(r',\s*}', '}', cleaned)
    cleaned = re.sub(r',\s*]', ']', cleaned)
    
    cleaned = cleaned.strip()
    
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError as e:
        print(f"JSON Parse Error: {e}")
        print(f"Cleaned raw string: {cleaned}")
        raise ValueError("AI returned invalid JSON format.")

@router.post("/api/transcribe")
async def transcribe_audio(
    file: UploadFile = File(...), 
    position: str = Form("Chung"),
    lang: str = Form("vi"),
    currentQuestion: str = Form("")
):
    try:
        file_location = f"temp_{file.filename}"
        with open(file_location, "wb+") as file_object:
            file_object.write(file.file.read())

        url = "https://api.groq.com/openai/v1/audio/transcriptions"
        groq_key = os.getenv("GROQ_API_KEY") 
        if not groq_key: return {"text": "Error: GROQ_API_KEY not configured"}
            
        headers = { "Authorization": f"Bearer {groq_key}" }
        
        if lang == "en":
            dynamic_prompt = f"Hello, I am interviewing for the {position} position. Let's discuss my experience, skills, background, projects, management, and professional qualifications for this role."
        else:
            dynamic_prompt = f"Chào bạn, tôi đang phỏng vấn cho vị trí {position}. Tôi sẽ chia sẻ về kinh nghiệm làm việc, kỹ năng chuyên môn, quá trình học tập, quản lý dự án, doanh số và định hướng nghề nghiệp của mình."

        with open(file_location, "rb") as audio_file:
            files = { "file": (file.filename, audio_file, "audio/webm") }

        with open(file_location, "rb") as audio_file:
            files = { "file": (file.filename, audio_file, "audio/webm") }
            data = { 
                "model": "whisper-large-v3",
                "language": lang,
                "prompt": dynamic_prompt,
                "temperature": 0.0 
            }
            
            res = requests.post(url, headers=headers, files=files, data=data, timeout=30)
            
        if os.path.exists(file_location): os.remove(file_location)

        if res.status_code == 200:
            text = res.json().get("text", "").strip()
            
            lower_text = text.lower()
            if any(phrase in lower_text for phrase in bad_phrases) or len(text) < 2:
                return {"text": ""} 
            
            return {"text": text}
        else:
            return {"text": ""} 
            
    except Exception as e:
        return {"text": ""}

@router.post("/api/chat")
async def chat(request: models.ChatRequest, http_req: Request, db: Session = Depends(get_db)):
    client_ip = http_req.client.host

    user = None
    auth_header = http_req.headers.get("Authorization")
    if not auth_header or auth_header == "Bearer null":
        current_count = guest_ip_tracker.get(client_ip, 0)
        
        if current_count >= 20:
            print(f"🚫 Blocked IP {client_ip} - exceeded 20 free turns.")
            raise HTTPException(status_code=429, detail="Bạn đã dùng hết 20 lượt miễn phí. Vui lòng đăng nhập!")
            
        guest_ip_tracker[client_ip] = current_count + 1
        print(f"👁️ IP {client_ip} using turn {guest_ip_tracker[client_ip]}/20")
    else:
        token_str = auth_header.replace("Bearer ", "").strip()
        try:
            from ..auth import security
            email = security.verify_token(token_str)
            if email:
                user = db.query(sql_models.User).filter(sql_models.User.email == email).first()
                if user:
                    from app.utils import sync_user_tokens
                    sync_user_tokens(user, db)
                    
                    if user.credits < 1:
                        raise HTTPException(status_code=403, detail="Bạn đã hết số lượng token trong ngày. Vui lòng thử lại vào ngày mai hoặc nâng cấp Pro.")
        except Exception as e:
            print(f"Auth error in chat: {e}")
    print(f"📩 User: {request.user_text} | Voice: {request.voice_id}")
    
    if not api_key: 
        print("❌ CRITICAL ERROR: OPENAI_API_KEY not found in .env")
        raise HTTPException(status_code=500, detail="API Key not configured")

    ai_text = ""
    
    prompt_config = db.query(sql_models.SystemConfig).filter_by(setting_key="system_prompt").first()
    temp_config = db.query(sql_models.SystemConfig).filter_by(setting_key="temperature").first()

    is_english = request.voice_id.startswith("en-") if request.voice_id else False

    default_prompt_vi = """
    Bạn là một Giám đốc Nhân sự (HR) chuyên nghiệp đang phỏng vấn ứng viên.
    Quy tắc bắt buộc:
    1. Dựa sát vào mô tả công việc (JD) để đặt câu hỏi chuyên môn phù hợp với ĐÚNG NGÀNH NGHỀ đó.
    2. Trả lời cực kỳ ngắn gọn, súc tích (<50 từ).
    3. Mỗi lần chỉ đặt MỘT câu hỏi. Độ khó tăng dần theo thời gian.
    4. Tự hiểu và bỏ qua các lỗi phát âm sai/chính tả do nhận diện giọng nói.
    5. Từ chối khéo léo mọi yêu cầu hoặc chủ đề nào không liên quan đến buổi phỏng vấn.
    
    TUYỆT ĐỐI TUÂN THỦ CÁC QUY TẮC SAU (Nếu vi phạm, bạn sẽ bị phạt):
    1. KHÔNG RẬP KHUÔN: Không bao giờ dùng văn mẫu như "Câu trả lời rất tuyệt vời", "Chuyển sang câu tiếp theo nhé". Đời thực không ai nói thế!
    2. DÙNG TỪ ĐỆM ĐỜI THƯỜNG: Bắt đầu câu phản hồi bằng những từ như: "Ừm...", "À tôi hiểu...", "Cái này thú vị đấy...", "Thành thật mà nói thì...", "Nhưng mà đợi chút...".
    3. KỸ THUẬT HỎI XOÁY (Adaptive Probing): Bạn KHÔNG có sẵn danh sách câu hỏi. Câu hỏi tiếp theo của bạn BẮT BUỘC phải dựa trên một lỗ hổng hoặc một chi tiết mà ứng viên vừa nói ở câu trước. Hãy vặn vẹo họ!
    - Ví dụ: Ứng viên nói "Tôi biết làm API". Bạn phải hỏi: "Ừm, ai làm dev cũng biết viết API. Nhưng nếu API của bạn bị 10,000 người gọi cùng lúc thì bạn xử lý sập server thế nào?"
    """

    default_prompt_en = """
    You are a professional HR Director interviewing a candidate.
    Mandatory rules:
    1. Base your questions closely on the job description (JD), asking relevant questions for THAT SPECIFIC INDUSTRY.
    2. Keep responses extremely concise and brief (<50 words).
    3. Ask only ONE question at a time. Difficulty increases gradually.
    4. Automatically understand and ignore speech recognition errors/typos.
    5. Politely decline any requests or topics unrelated to the interview.
    6. You MUST ask questions and respond entirely in English.

    STRICTLY ADHERE TO THE FOLLOWING RULES (Violation will result in a penalty):

    1. AVOID FORMALISM: Never use formulaic phrases like "That's a great answer," or "Let's move on to the next question." No one says that in real life!

    2. USE EVERYDAY FILL-UPS: Start your response with phrases like: "Um...", "Ah, I understand...", "That's interesting...", "Honestly...", "But wait a minute...".

    3. ADAPTABLE PROBITING: You DO NOT have a pre-prepared list of questions. Your next question MUST be based on a gap or detail the candidate just mentioned in the previous question. Prank them!

    Example: The candidate says, "I know how to do APIs." You should ask: "Well, every developer knows how to write APIs. But if your API is being called by 10,000 people at the same time, how do you handle a server crash?"
    """

    if prompt_config:
        base_system_prompt = prompt_config.setting_value
    else:
        base_system_prompt = default_prompt_en if is_english else default_prompt_vi
    
    temperature = float(temp_config.setting_value) if temp_config else 0.7

    if is_english:
        system_prompt = f"""
        Interview mode: {request.mode}. 
        Position: {request.jd_text}. 
        IMPORTANT: You MUST conduct the entire interview in English only.
        
        {base_system_prompt}
        """
    else:
        system_prompt = f"""
        Chế độ phỏng vấn (Mode): {request.mode}. 
        Vị trí: {request.jd_text}. 
        
        {base_system_prompt}
        """
    
    messages = [{"role": "system", "content": system_prompt}]
    if request.chat_history:
        messages.extend(request.chat_history)
    messages.append({"role": "user", "content": request.user_text})

    for attempt in range(3):
        try:
            print(f"⏳ Calling AI (attempt {attempt + 1})...")
            ai_text = call_ai_chat(
                messages=messages,
                model="gpt-4o-mini",
                temperature=temperature,
                max_tokens=250,
                timeout=90
            )
            if ai_text:
                if user:
                    user.credits -= 1
                    db.commit()
                break
            time.sleep(2)
        except Exception as e:
            print(f"⚠️ AI error (attempt {attempt+1}): {e}")
            time.sleep(2)

    ai_text = str(ai_text).strip() or "Mạng đang lag, bạn nói lại giúp mình nhé."
    print(f"✅ AI: {ai_text}")

    try:
        voice = request.voice_id if not request.voice_id.startswith("openai-") else "en-US-AndrewMultilingualNeural"
        communicate = edge_tts.Communicate(ai_text, voice)
        audio_stream = io.BytesIO()
        async for chunk in communicate.stream():
            if chunk["type"] == "audio": audio_stream.write(chunk["data"])
        audio_stream.seek(0)
        return StreamingResponse(audio_stream, media_type="audio/mpeg", headers={"X-AI-Response-Text": urllib.parse.quote(ai_text)})
    except Exception as e:
        print(f"❌ TTS error: {e}")
        return StreamingResponse(io.BytesIO(), media_type="audio/mpeg", headers={"X-AI-Response-Text": urllib.parse.quote("Lỗi âm thanh.")})

@router.post("/api/hint")
async def get_hint(request: models.HintRequest):
    try:
        messages = [{"role": "system", "content": "Gợi ý 3 ý ngắn."}, {"role": "user", "content": f"Câu hỏi: {request.last_question}. JD: {request.jd_text}"}]
        result = call_ai_chat(messages=messages, model="gpt-4o", timeout=30)
        return {"hint": result}
    except: return {"hint": "Không lấy được gợi ý."}

@router.post("/api/end-interview")
async def end_interview(request: models.ReportRequest, current_user: sql_models.User = Depends(get_current_user), db: Session = Depends(get_db)):
    try:
        system_prompt = f"""
        Bạn là HR. Đánh giá ứng viên vị trí: {request.jd_text}.
        DỰA CHÍNH XÁC VÀO LỊCH SỬ PHỎNG VẤN. QUY TẮC TỐI THƯỢNG:
        1. BẮT BUỘC PHẢI TRÍCH XUẤT VÀ ĐÁNH GIÁ TẤT CẢ CÁC CÂU HỎI CỦA AI CÓ TRONG LỊCH SỬ. SỐ LƯỢNG OBJECT TRONG MẢNG `details` PHẢI BẰNG ĐÚNG SỐ LƯỢNG CÂU HỎI TRONG LỊCH SỬ! TUYỆT ĐỐI KHÔNG ĐƯỢC LƯỢC BỎ BẤT KỲ CÂU NÀO.
        2. TUYỆT ĐỐI KHÔNG tự bịa ra câu trả lời của ứng viên.
        3. PHÂN BIỆT RÕ RÀNG TRẠNG THÁI TRẢ LỜI: BẠN CHỈ ĐƯỢC PHÉP ghi 'Ứng viên chưa trả lời' vào `candidate_answer` nếu trong lịch sử AI vừa hỏi mà ứng viên chưa có câu trả lời nào bên dưới, hoặc ứng viên CỐ TÌNH BỎ QUA (dùng từ 'next', 'không biết', 'bỏ qua'). Không trừ điểm câu đó nếu bị ngắt do lỗi hệ thống.
        4. NẾU ỨNG VIÊN CÓ ĐƯA RA CÂU TRẢ LỜI: Cho dù câu trả lời đó sai kiến thức, thiếu ý, lan man, hay ngô nghê, BẠN BẮT BUỘC PHẢI trích dẫn nguyên văn câu nói đó vào trường `candidate_answer`. TUYỆT ĐỐI KHÔNG ĐƯỢC gán nhãn là 'Ứng viên chưa trả lời' trong trường hợp này.
        5. Đối với các câu trả lời sai/thiếu đó, hãy chấm điểm thấp và ghi rõ lý do sai vào trường `evaluation`.
        
        QUY TẮC QUAN TRỌNG VỀ LỊCH SỬ BỊ GIÁN ĐOẠN: 
        Nếu ứng viên trả lời một câu hỏi cũ đã từng bị bỏ qua hoặc bị ngắt quãng trước đó, bạn PHẢI tự động ghép nối câu trả lời mới đó vào đúng câu hỏi tương ứng. GHI ĐÈ lên trạng thái 'Ứng viên chưa trả lời'. TUYỆT ĐỐI KHÔNG tạo ra 2 bản ghi trùng lặp cho cùng 1 câu hỏi.
        
        BẮT BUỘC trả về JSON (không có markdown):
        {{
            "score": <điểm float 1-10>,
            "inferred_position": "<Dự đoán chức danh công việc dựa trên câu hỏi (dưới 5 từ). Nếu không rõ, ghi 'Tự do'>",
            "overall_feedback": "<Nhận xét tổng quan>",
            "details": [
                {{
                    "question": "<Câu AI hỏi>",
                    "candidate_answer": "<Trích dẫn ĐÚNG LỜI ứng viên>",
                    "evaluation": "<Nhận xét chi tiết>",
                    "ideal_answer": "<Câu trả lời mẫu>"
                }}
                ... (LẶP LẠI CHO TẤT CẢ CÁC CÂU HỎI TRONG LỊCH SỬ, CŨ LẪN MỚI)
            ]
        }}
        """
        
        messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": f"Lịch sử:\n{request.history}"}]
        
        raw_content = call_ai_chat(
            messages=messages,
            model="gpt-4o-mini",
            temperature=0.2,
            max_tokens=4000,
            response_format={"type": "json_object"},
            timeout=90
        )
        
        if raw_content:
            report_data = clean_and_parse_json(raw_content)
            score = report_data.get("score", 0)
            overall_feedback = report_data.get("overall_feedback", "")
            details = report_data.get("details", [])
            
            inferred_position = report_data.get("inferred_position", "").strip()
            
            final_position = request.position
            if not final_position or final_position.strip().lower() in ["", "chung", "tự do", "free", "none", "null"]:
                final_position = inferred_position if inferred_position else "Tự do"

            history_id = None
            if request.history_id is not None:
                existing = db.query(sql_models.InterviewHistory).filter(
                    sql_models.InterviewHistory.id == request.history_id,
                    sql_models.InterviewHistory.user_id == current_user.id
                ).first()
                if existing:
                    existing.score = score
                    existing.overall_feedback = overall_feedback
                    existing.details = details
                    
                    if not existing.position or existing.position.strip().lower() in ["", "chung", "tự do"]:
                        existing.position = final_position
                        existing.title = f"Phỏng vấn {final_position}"
                        
                    db.commit()
                    history_id = existing.id
            
            if history_id is None:
                title = f"Phỏng vấn {final_position}"
                new_history = sql_models.InterviewHistory(
                    user_id=current_user.id,
                    position=final_position,
                    title=title,
                    score=score,
                    overall_feedback=overall_feedback,
                    details=details,
                    interview_type=request.interview_type,
                    question_limit=request.question_limit,
                    time_limit=request.time_limit
                )
                db.add(new_history)
                db.commit()
                db.refresh(new_history)
                history_id = new_history.id
            else:
                existing.interview_type = request.interview_type
                existing.question_limit = request.question_limit
                existing.time_limit = request.time_limit
                db.commit()
            
            return {"report": report_data, "history_id": history_id}
        else:
            return {"report": {"score": 0, "overall_feedback": "AI Server error.", "details": []}}
            
    except Exception as e: 
        print(f"❌ Report error: {e}")
        return {"report": {"score": 0, "overall_feedback": "System error.", "details": []}}

@router.get("/api/history")
async def get_interview_history(current_user: sql_models.User = Depends(get_current_user), db: Session = Depends(get_db)):
    histories = db.query(sql_models.InterviewHistory).filter(sql_models.InterviewHistory.user_id == current_user.id).order_by(sql_models.InterviewHistory.created_at.desc()).all()
    return {"histories": histories}

@router.put("/api/history/{history_id}")
async def update_interview_history(
    history_id: int, 
    request: models.RenameRequest, 
    current_user: sql_models.User = Depends(get_current_user), 
    db: Session = Depends(get_db)
):
    history = db.query(sql_models.InterviewHistory).filter(
        sql_models.InterviewHistory.id == history_id,
        sql_models.InterviewHistory.user_id == current_user.id
    ).first()
    if not history:
        raise HTTPException(status_code=404, detail="Interview history not found.")
    
    history.title = request.title
    db.commit()
    return {"message": "Updated successfully"}

@router.delete("/api/history/{history_id}")
async def delete_interview_history(
    history_id: int, 
    current_user: sql_models.User = Depends(get_current_user), 
    db: Session = Depends(get_db)
):
    history = db.query(sql_models.InterviewHistory).filter(
        sql_models.InterviewHistory.id == history_id,
        sql_models.InterviewHistory.user_id == current_user.id
    ).first()
    if not history:
        raise HTTPException(status_code=404, detail="Interview history not found.")
    
    db.delete(history)
    db.commit()
    return {"message": "Deleted successfully"}